config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  d_helix:
    src: config/helix
    dst: ~/.config/helix
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
  d_tmux:
    src: config/tmux
    dst: ~/.config/tmux
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  d_oh-my-zsh:
    src: oh-my-zsh
    dst: ~/.oh-my-zsh
  f_p10k.zsh:
    src: p10k.zsh
    dst: ~/.p10k.zsh
profiles:
  default:
    dotfiles:
    - d_helix
    - f_starship.toml
    - d_tmux
    - f_gitconfig
    - f_zshrc
    - d_oh-my-zsh
    - f_p10k.zsh
